import requests
data = [
  ('dataset', ' STA_L2_MAGPLASMA_1M STB_L2_MAGPLASMA_1M'),
  ('start', '2014/06/01 18:00:00.000'),
  ('stop', '2014/06/18 18:00:00.000'),
  ('bin_value', '15'),
  ('time_unit', 'min'),
  ('missval', 'fillval'),
  ('spike_opt', 'none'),
  ('index', 'sp_phys'),
  ('nobin_spike_opt', 'light'),
  ('spinner', '1'),
  ('autoChecking', 'on'),
  ('action', 'list'),
  ('var', 'STA_L2_MAGPLASMA_1M BTOTAL'),
  ('var', 'STA_L2_MAGPLASMA_1M Np'),
  ('var', 'STA_L2_MAGPLASMA_1M Vp'),
  ('var', 'STA_L2_MAGPLASMA_1M Tp'),
  ('var', 'STA_L2_MAGPLASMA_1M Vth'),
  ('var', 'STA_L2_MAGPLASMA_1M Vn_Over_V_RTN'),
  ('var', 'STA_L2_MAGPLASMA_1M Beta'),
  ('var', 'STA_L2_MAGPLASMA_1M Total_Pressure'),
  ('var', 'STA_L2_MAGPLASMA_1M Clock_Angle'),
  ('var', 'STB_L2_MAGPLASMA_1M BFIELDRTN'),
  ('var', 'STB_L2_MAGPLASMA_1M BTOTAL'),
  ('var', 'STB_L2_MAGPLASMA_1M HAE'),
  ('var', 'STB_L2_MAGPLASMA_1M HEE'),
  ('var', 'STB_L2_MAGPLASMA_1M HEEQ'),
  ('var', 'STB_L2_MAGPLASMA_1M CARR'),
  ('var', 'STB_L2_MAGPLASMA_1M RTN'),
  ('var', 'STB_L2_MAGPLASMA_1M R'),
  ('var', 'STB_L2_MAGPLASMA_1M Np'),
  ('var', 'STB_L2_MAGPLASMA_1M Vp'),
  ('var', 'STB_L2_MAGPLASMA_1M Tp'),
  ('var', 'STB_L2_MAGPLASMA_1M Vth'),
  ('var', 'STB_L2_MAGPLASMA_1M Vr_Over_V_RTN'),
  ('var', 'STB_L2_MAGPLASMA_1M Vt_Over_V_RTN'),
  ('var', 'STB_L2_MAGPLASMA_1M Vn_Over_V_RTN'),
  ('var', 'STB_L2_MAGPLASMA_1M Vp_RTN'),
  ('var', 'STB_L2_MAGPLASMA_1M Entropy'),
  ('var', 'STB_L2_MAGPLASMA_1M Beta'),
  ('var', 'STB_L2_MAGPLASMA_1M Total_Pressure'),
  ('var', 'STB_L2_MAGPLASMA_1M Cone_Angle'),
  ('var', 'STB_L2_MAGPLASMA_1M Clock_Angle'),
  ('var', 'STB_L2_MAGPLASMA_1M Magnetic_Pressure'),
  ('var', 'STB_L2_MAGPLASMA_1M Dynamic_Pressure'),
  ('png', '1'),
]
response = requests.post('https://cdaweb.gsfc.nasa.gov/cgi-bin/eval3.cgi', data=data)
print(response.text)